### ISSUE TITLE
Volkswagen Caddy Pickup 1,6mpi 2001  getSKC not working

### ISSUE THREAD

**Issue by Lofsim** [gmenounos/kw1281test#100]
Hello people!

I am trying to retrieve my SKC, but I am not being able to get this program to work. When I try the "kw1281test.exe com1 9600 17 getSKC" command, I get stuck on the controller not waking up. In VCDS when I select the instruments module, it says "no response from the controller!". Could this be the reason for this fault?. I tried to get the skc from the immobiliser, but all I get is this:
C:\Users\simlof02\Documents>Kw1281test.exe com1 2400 25 getskc
KW1281Test: Yesterday's diagnostics...Today.

Version 0.99.1-beta (https://github.com/gmenounos/kw1281test/releases)
Args: com1 2400 25 getskc
OSVersion: Microsoft Windows NT 10.0.19045.0
.NET Version: 8.0.6
Culture: sv-SE
Opening serial port com1
Sending wakeup message
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 1H0953257 B IMMO VWZ3Z0Y0274751 V00
Software Coding 02400, Workshop Code: 00186
Unsupported cluster: 1H0953257 B IMMO VWZ3Z0Y0274751 V00
Software Coding 02400, Workshop Code: 00186
Sending EndCommunication block

Is my code in here or do I need to try something else??
My system is Windows 10 and the cable is a VAG KKL (KKL VAG-COM for 409.1)

Also when I tried to run any other command after that one, I get windows pop-ups telling me I cant run this application on this pc, and in the command prompt it says "access denied".

**Comment by kerekt** [comment]
This is old caddy, dashboard is "golf3 style", 17 not have diagnostic

**Comment by kerekt** [comment]
SKC in immobox on address 25 
Inside  Motorola 68HC05 mcu, code inside. 
Usually soldering job.

**Comment by gmenounos** [comment]
@kerekt thanks for the info.

**Comment by poure-1** [comment]
@Lofsim this unit is now supported in latest version. Can you give it a try? 
You need at least one working key
