### ISSUE TITLE
6Q0920804J Unsupported cluster | Polo IV 9N3 2008

### ISSUE THREAD

**Issue by crowdyy** [gmenounos/kw1281test#106]
Hello,
I have a polo 4 9n3 2008.
I have this problem when i tried to get skc code

Version 0.99.3-beta (https://github.com/gmenounos/kw1281test/releases)
Args: COM2 10400 17 GetSKC
OSVersion: Microsoft Windows NT 10.0.19045.0
.NET Version: 8.0.11
Culture: fr-FR
Opening serial port COM2
Sending wakeup message
Reading sync byte
The operation has timed out.
Retrying wakeup message...
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 6Q0920804J  KOMBIINSTRUMENT AGD V05
Software Coding , Workshop Code: 00000
Unsupported cluster: 6Q0920804J  KOMBIINSTRUMENT AGD V05
Software Coding , Workshop Code: 00000
Sending EndCommunication block

**Comment by gmenounos** [comment]
> 6Q0920804J KOMBIINSTRUMENT AGD V05

"AGD" means that it's a Marelli cluster, not VDO like the other Polo clusters that kw1281test supports. I don't have any Marelli Polo clusters so I can't add support for them at this time. Sorry.

**Comment by crowdyy** [comment]
Okay thank's but i have another question.
Can i dump eeprom with another command ?

**Comment by gmenounos** [comment]
I doubt it. Usually the cluster needs to be unlocked with a special command before the EEPROM can be dumped and I don't know what special command would unlock that type of cluster.

**Comment by crowdyy** [comment]
oh ok, so how do I get the SKC code, because I need to quickly program my key because I broke my only transponder

**Comment by gmenounos** [comment]
Unfortunately I don't know. I'm in the US and we don't have Polos here. The 2 Polo clusters I have (both VDO), I had to buy from Europe via eBay. You might try asking here: http://nefariousmotorsports.com/forum/

**Comment by gmenounos** [comment]
Or here: https://www.digital-kaos.co.uk/
Or here: https://uk-polos.net/

**Comment by crowdyy** [comment]
Thank you very much, I will try these sites, I hope I can program my new key.

**Comment by crowdyy** [comment]
> With some clusters you adapt new keys on 15 (Immobilizer) instead of 17 (cluster). It sounds like your cluster works like that.

Ok thank you, do you know the channel to put in the adaptation of immobilizer?
