### ISSUE TITLE
immobilizer key programming

### ISSUE THREAD

**Issue by robertsmd** [gmenounos/kw1281test#11]
Would love a feature for programming immobilizer chips on new key fobs

**Comment by gmenounos** [comment]
It's already supported using the AdaptationSave command:
https://forums.tdiclub.com/index.php?threads/free-vds-pro-vagtacho-alternative.509151/post-5680841
Depending on whether your car is Immo2 or Immo3, the procedure is slightly different.

**Comment by gmenounos** [comment]
kw1281test only supports communication with the vehicle over the K-Line. I'm pretty sure that immo4 and require communication over the CAN bus, so kw1281test will only work with Immo3 and earlier. Also, both my vehicles are MKIV Vw / Immo3 so I don't have a way to test anything newer.
