### ISSUE TITLE
GetSKC not returning results, or a failure on Mk4 City Golf cluster

### ISSUE THREAD

**Issue by ChrstphrR** [gmenounos/kw1281test#13]
## Description of the Issue:

Having an issue with some of my newer (Mk4.5 City Golf/Jetta) clusters, in that they are unable to pull the small 144 byte EEPROM dumps and then calculate the SKC when I invoke GetSKC.

- No 144 byte binary is dumped from the cluster to screen, or to file.
- No SKC is looked up, or calculated
- No SKC code is displayed before the "End Communication" header.

Running on ubuntu 21.10 x64
Linux Kernel is:  5.16.3-051603-generic #202201270732 SMP PREEMPT Thu Jan 27 12:37:40 UTC 

My copy of kw1281test is run from sources cloned from the master github repository.
"git pull" indicates that my copy is up to date.

I did compile my own binaries, but the same results occur using the binary, or using "dotnet run" on the source files.

### GetSKC
(cable serial number altered to my example s/n to protect the innocent and the guilty alike)
```
# ./kw1281test ACDCBLAH 10400 17 GetSKC
Version 0.71-beta (https://github.com/gmenounos/kw1281test/releases)
Args: ACDCBLAH 10400 17 GetSKC
OSVersion: Unix 5.16.3.51603
.NET Version: 6.0.1
Culture: en-CA
Opening FTDI serial port ACDCBLAH
Sending wakeup message
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 1J0920807   KOMBI+WEGFAHRSP VDO V03
Software Coding 09334, Workshop Code: 91584
Sending EndCommunication block
```
Note how no memory is dumped, no SKC is calculated.  No apparent errors occur or are displayed to the user.

### ReadIdent
```
# ./kw1281test ACDCBLAH 10400 17 ReadIdent
Version 0.71-beta (https://github.com/gmenounos/kw1281test/releases)
Args: ACDCBLAH 10400 17 ReadIdent
OSVersion: Unix 5.16.3.51603
.NET Version: 6.0.1
Culture: en-CA
Opening FTDI serial port ACDCBLAH
Sending wakeup message
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 1J0920807   KOMBI+WEGFAHRSP VDO V03
Software Coding 09334, Workshop Code: 91584
Sending ReadIdent block
Ident: 9BWEL41J874011042     VWZ7Z0G5049692
Sending EndCommunication block
```

### ReadSoftwareVersion
```
# ./kw1281test ACDCBLAH 10400 17 ReadSoftwareVersion
Version 0.71-beta (https://github.com/gmenounos/kw1281test/releases)
Args: ACDCBLAH 10400 17 ReadSoftwareVersion
OSVersion: Unix 5.16.3.51603
.NET Version: 6.0.1
Culture: en-CA
Opening FTDI serial port ACDCBLAH
Sending wakeup message
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 1J0920807   KOMBI+WEGFAHRSP VDO V03
Software Coding 09334, Workshop Code: 91584
Sending Custom "Read Software Version" blocks
Sending Custom "Unlock Additional Commands" block
00: VWK503LL $00 $09 
01: $58 $20 
02: $13 $0B $02 $0D $35 $04 
03: VW/Sk LL ROM-Maske  
Sending EndCommunication block
```

If there's more that I need to pass on for analysis, please ask.  I'm in the midst of dumping the EEPROM and ROM dumps after I write this.

**Comment by gmenounos** [comment]
It was expecting your cluster part number to end with 1 or 2 letters. To fix it, try changing line 754 of Program.cs:

Change:
"\\b(\\d[a-zA-Z])\\d9(\\d{2})\\d{3}[a-zA-Z][a-zA-Z]?\\b"

To:
"\\b(\\d[a-zA-Z])\\d9(\\d{2})\\d{3}[a-zA-Z]{0,2}\\b"

**Comment by ChrstphrR** [comment]
That was it!

And yes, it was oddball that the cluster has no revision number on it's part number.   The other one that had issues was also a non-revision lettered part as well.

Thank you!
