### ISSUE TITLE
Unexpected sync byte: Expected $55, Actual $A5 (2004 Audi B6 A4)

### ISSUE THREAD

**Issue by k7saru** [gmenounos/kw1281test#21]
2004 Audi A4 -- Using Blue VAG KKL cable with the CH340 chip

When reading the sync byte following the wakeup message, it returns this error:

        Caught: System.InvalidOperationException Unexpected sync byte: Expected $55, Actual $A5

The value of "Actual" changes with an adjusted com port baud rate but I haven't been able to get it working. 
 (in device manager and then the command to match)

VCDS Lite is functional so I believe the drivers aren't the issue, unless they still could be.

Here's the full picture of what I'm seeing:

**********
C:\Users\User\Desktop\kw1281test_0.74>kw1281test.exe com3 9600 17 GetSKC
KW1281Test: Yesterday's diagnostics...Today.

Version 0.74-beta (https://github.com/gmenounos/kw1281test/releases)
Args: com3 9600 17 GetSKC
OSVersion: Microsoft Windows NT 10.0.19044.0
.NET Version: 6.0.2
Culture: en-US
Opening serial port com3
Sending wakeup message
Wakeup duration: 2 seconds
Reading sync byte
Caught: System.InvalidOperationException Unexpected sync byte: Expected $55, Actual $A5
Unhandled exception: System.InvalidOperationException: Unexpected sync byte: Expected $55, Actual $A5
   at BitFab.KW1281Test.KwpCommon.WakeUp(Byte controllerAddress, Boolean evenParity) in C:\Users\gmeno\src\kw1281test\KwpCommon.cs:line 75
   at BitFab.KW1281Test.Tester.Kwp1281Wakeup(Boolean evenParityWakeup) in C:\Users\gmeno\src\kw1281test\Tester.cs:line 31
   at BitFab.KW1281Test.Tester.GetSkc() in C:\Users\gmeno\src\kw1281test\Tester.cs:line 427
   at BitFab.KW1281Test.Program.Run(String[] args) in C:\Users\gmeno\src\kw1281test\Program.cs:line 241
   at BitFab.KW1281Test.Program.Main(String[] args) in C:\Users\gmeno\src\kw1281test\Program.cs:line 26
***********

After trying again with different releases, testing the .NET compilation along with V0.66, they both return this error with different values for “Actual”’. The 0.66 returns it as $AD while .NET returns as $A9

**Comment by gmenounos** [comment]
Unexpected sync byte usually means you're not using the correct baud rate. Kw1281test doesn't set the baud rate automatically like VCDS does. Try 10400 instead of 9600 and see if that works.

**Comment by k7saru** [comment]
Thank you for taking the time to answer! And so fast too :D I will try this

**Comment by k7saru** [comment]
This solved the connection issue! Using the kw1281test-master version It did however return that I have an unsupported cluster. 
“Unsupported cluster: 8E0920950L KOMBI+WEGFAHRS. RB4 D37
Software Coding 03200, Workshop Code: 08902” 
Will there be future support for this unit? Thank you

**Comment by gmenounos** [comment]
I don't own any clusters of that type, but if I can find one cheap enough then it might be possible.

**Comment by k7saru** [comment]
Alright, I will continue with looking for my skc

**Comment by gmenounos** [comment]
I was able to get ahold of cheap RB4 cluster and have started researching how to get the SKC. If you have time, could you use the following command to dump the EEPROM to a file and then attach the file to this conversation?

.\kw1281test com3 10400 17 DumpRB8Eeprom 66560 1024

**Comment by k7saru** [comment]
Yes, I will try this soon as I’m back home in 2hr or so

**Comment by k7saru** [comment]
Ok I got it. Here's the file, I couldn't get the .bin file attached here so I made a public g-drive folder.
 [https://drive.google.com/drive/folders/1FqYexmgl0-Z-7WDNjVWZCXs0i1IM6GbI?usp=sharing](url)

**Comment by gmenounos** [comment]
Ok, that looks good. Can you now run this command and post or upload the .bin file?

.\kw1281test.exe COM3 10400 17 DumpRB8Eeprom 66640 2

**Comment by k7saru** [comment]
Ok I added that one to the drive as well.  It's RB8_$010450_eeprom.bin
[https://drive.google.com/drive/folders/1FqYexmgl0-Z-7WDNjVWZCXs0i1IM6GbI?usp=sharing](https://github.com/gmenounos/kw1281test/issues/url)

**Comment by gmenounos** [comment]
Could you attach the kw1281test.log file also?

**Comment by k7saru** [comment]
I’ll be home in an hour and get that uploaded. Also where can I find the file? Is it something I get using a command? I’m not at my computer rn but I don’t think there’s any log file in the folder with the kw1281test app

**Comment by gmenounos** [comment]
It would normally be in the same folder as kw1281test.

**Comment by k7saru** [comment]
[KW1281Test.log](https://github.com/gmenounos/kw1281test/files/9492395/KW1281Test.log)
Ok here it is. If you need me to I can run it again with a new program so it only has the two eeprom dumps without the other things.

**Comment by gmenounos** [comment]
I've added some support for RB4 clusters: https://github.com/gmenounos/kw1281test/releases/tag/v0.77-beta

But I was only able to test it on the single RB4 cluster that I own so I can't guarantee that it'll work on yours (but I'm pretty sure it will).

However, if you want a better tested tool, you can try to find a copy of VAG EEPROM 1.19. There are some instructions on how to use it here: https://www.audizine.com/forum/showthread.php/722211-is-there-a-good-DIY-out-there-for-using-Vag-EEPROM-1-19-to-retrieve-SKC-s

**Comment by k7saru** [comment]
It works! It took a ferw tries but it got me my skc. Thank you so much!! I've attached the kw1281test.log file if you need it and will donate some cash since it worked.
[KW1281Test.log](https://github.com/gmenounos/kw1281test/files/9502123/KW1281Test.log)

I added my eeprom file backups to a g drive incase anyone corrupts theirs without one. Once again the cluster I have is a Bosch "KOMBI=WEGFAHRS. RB4 D37" 

There's a working copy of VAG EEPROM PROGRAMMER 1.19g in there as well because it was such a pain to get ahold of. I paid $20 dollars for a nonworking copy before finding a free working download that wasn't on a paywalled forum.
The drive:
https://drive.google.com/drive/folders/1aC1Y670H5xIdVWEqOo2Gkg9GRYywxhf1?usp=sharing
