### ISSUE TITLE
Hex v2 not working 

### ISSUE THREAD

**Issue by tsywyk** [gmenounos/kw1281test#25]
i cant seem to be able to install the driver for the hex v2 from ross tech. the driver just seems to not show up. how should i go about this?

**Comment by gmenounos** [comment]
Hex V2 doesn't support the VCP drivers.

**Comment by tsywyk** [comment]
So I'll need a different cable then, alrighty.. thank you With regardsTyler
-------- Original message --------From: Greg Menounos ***@***.***> Date: 2022-11-10  1:15 p.m.  (GMT-05:00) To: gmenounos/kw1281test ***@***.***> Cc: tsywyk ***@***.***>, Author ***@***.***> Subject: Re: [gmenounos/kw1281test] Hex v2 not working  (Issue #25) 
Hex V2 doesn't support the VCP drivers.

**Comment by gmenounos** [comment]
Yes. Ross Tech mentions here that the HEX-V2 isn't supported: https://www.ross-tech.com/vag-com/usb/virtual-com-port.php
I've had good luck with this one: https://www.amazon.com/gp/product/B00K6498D0
