### ISSUE TITLE
key is incorrect ?

### ISSUE THREAD

**Issue by tsywyk** [gmenounos/kw1281test#26]
C:\Users\ty\Desktop\kw1281test_0.78-beta_Win10>.\kw1281test.exe COM9 10400 17 GetSKC
KW1281Test: Yesterday's diagnostics...Today.

Version 0.78-beta (https://github.com/gmenounos/kw1281test/releases)
Args: COM9 10400 17 GetSKC
OSVersion: Microsoft Windows NT 10.0.18363.0
.NET Version: 6.0.8
Culture: en-CA
Opening serial port COM9
Sending wakeup message
Wakeup duration: 2 seconds
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 1J0920800L  A4-KOMBIINSTR. VDO V59
Software Coding 07342, Workshop Code: 00066
Sending ReadIdent block
Sending Custom "Read Software Version" blocks
Sending Custom "Unlock Additional Commands" block
00: V599LLA  $00 $01
01: $56 $35 $39 $39 $4C $4C $41 $20 $00 $01
02: $56 $35 $39 $39 $4C $4C $41 $20 $00 $01
03: V599LLA  $00 $01
Sending Custom "Unlock partial EEPROM read" block
Unlock code for software version V599LLA  01.00 is 38 3F 40 35
Please report this to the program maintainer.
Sending Custom "Need Seed/Key?" block
Sending Custom "Seed request" block
Sending Custom "Need Seed/Key?" block
Failed to unlock cluster.
Saving EEPROM dump to IMMO-IDENTNR_VWZ7Z0Y2466235________$0090_eeprom.bin
Sending ReadEeprom block (Address: $0090, Count: $10)
Received "Read ROM/EEPROM Response" block: 36 4E 30 39 30 39 39 30 31 20 31 4A 30 39 32 30
Sending ReadEeprom block (Address: $00A0, Count: $10)
Received "Read ROM/EEPROM Response" block: 38 30 30 4C 20 FF 41 34 56 35 39 FF 56 57 5A 37
Sending ReadEeprom block (Address: $00B0, Count: $10)
Received "Read ROM/EEPROM Response" block: 5A 30 59 32 34 36 36 32 33 35 73 94 56 57 5A 37
Sending ReadEeprom block (Address: $00C0, Count: $10)
Received "Read ROM/EEPROM Response" block: 5A 30 59 32 34 36 36 32 33 35 73 94 56 57 5A 37
Sending ReadEeprom block (Address: $00D0, Count: $10)
Received "Read ROM/EEPROM Response" block: 5A 30 59 32 34 36 36 32 33 35 73 94 FF FF FF FF
Sending ReadEeprom block (Address: $00E0, Count: $10)
Received "Read ROM/EEPROM Response" block: FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
Sending ReadEeprom block (Address: $00F0, Count: $10)
Received "Read ROM/EEPROM Response" block: FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
Sending ReadEeprom block (Address: $0100, Count: $0C)
Received "Read ROM/EEPROM Response" block: FF FF 16 25 16 25 16 25 17 25 17 25
Saved EEPROM dump to IMMO-IDENTNR_VWZ7Z0Y2466235________$0090_eeprom.bin
SKC: -06527
Sending EndCommunication block

it is telling me my SKC however when i go and use vcds it tells me the key is wrong and to turn vehicle off and to try again

**Comment by gmenounos** [comment]
Can you try Version 0.80-beta and see if that works?

https://github.com/gmenounos/kw1281test/releases/tag/v0.80-beta

**Comment by tsywyk** [comment]
> Can you try Version 0.80-beta and see if that works?
> 
> https://github.com/gmenounos/kw1281test/releases/tag/v0.80-beta

Worked perfect ! Thanks for the qucik turnaround !!!
