### ISSUE TITLE
Unable to read SKC off a VW Sharan 1997 Model

### ISSUE THREAD

**Issue by Souljarhboy** [gmenounos/kw1281test#29]
Hello,

I am trying read my car's SKC so that I can program additional keys to work with the immobilizer.

However, when I open CMD, change directory to the kw1281test folder and run '.\kw1281test.exe COM1 10400 17 GetSKC' (without the parenthesis),  I get the following error:

Version 0.76-beta (https://github.com/gmenounos/kw1281test/releases)
Args: COM1 10400 17 GetSKC
OSVersion: Microsoft Windows NT 10.0.19044.0
.NET Version: 6.0.8
Culture: en-US
Opening serial port COM1
Sending wakeup message
Wakeup duration: 2 seconds
Reading sync byte
Caught: System.InvalidOperationException Unexpected sync byte: Expected $55, Actual $95
Unhandled exception: System.InvalidOperationException: Unexpected sync byte: Expected $55, Actual $95
   at BitFab.KW1281Test.KwpCommon.WakeUp(Byte controllerAddress, Boolean evenParity) in C:\Users\gmeno\src\kw1281test\KwpCommon.cs:line 75
   at BitFab.KW1281Test.Tester.Kwp1281Wakeup(Boolean evenParityWakeup) in C:\Users\gmeno\src\kw1281test\Tester.cs:line 31
   at BitFab.KW1281Test.Tester.GetSkc() in C:\Users\gmeno\src\kw1281test\Tester.cs:line 428
   at BitFab.KW1281Test.Program.Run(String[] args) in C:\Users\gmeno\src\kw1281test\Program.cs:line 243
   at BitFab.KW1281Test.Program.Main(String[] args) in C:\Users\gmeno\src\kw1281test\Program.cs:line 26

Attached is the log.

I also tried it with the latest version of kw1281test (version 0.80-beta), still the same error message.

Please can I get help? Am I doing something wrong or is there something I am missing?

Thanks,

Kwento
[KW1281Test.log](https://github.com/gmenounos/kw1281test/files/10097849/KW1281Test.log)

**Comment by Souljarhboy** [comment]
Hi while awaiting a response, I have been trying different things, such as changing the baud rate. When I use 9600, I get the following:


Version 0.80-beta (https://github.com/gmenounos/kw1281test/releases)
Args: COM1 9600 17 GetSKC
OSVersion: Microsoft Windows NT 10.0.19045.0
.NET Version: 7.0.0
Culture: en-US
Opening serial port COM1
Sending wakeup message
Wakeup duration: 2 seconds
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 7MO919881   Kombiinstrument     053e
Software Coding 00116, Workshop Code: 00030
Unsupported cluster: 7MO919881   Kombiinstrument     053e
Software Coding 00116, Workshop Code: 00030
Sending EndCommunication block


Why does it say my cluster is unsupported? Please is there any way around it? Or any other app or software I could use?
My car is a 1997 Volkswagen Sharan VR6.
Thanks

**Comment by gmenounos** [comment]
> Why does it say my cluster is unsupported? Please is there any way around it? Or any other app or software I could use?
> My car is a 1997 Volkswagen Sharan VR6.

kw1281test supports several types of clusters made by different manufacturers: VDO, Bosch/Motometer, Magneti Marelli. Each type of cluster requires a different method to unlock the cluster to retrieve the SKC. Since your cluster doesn't appear to be made by any of the supported manufacturers, kw1281test has no idea how to retrieve the SKC. I don't have access to any Sharan clusters to test with, so it's pretty much impossible for me to add support for them.
