### ISSUE TITLE
Time out period expired.

### ISSUE THREAD

**Issue by blemiee** [gmenounos/kw1281test#30]
Hello, Ive been trying to use this software for awhile but i seem to be getting this error quite often, is there a way to fix this?

<img width="545" alt="image" src="https://user-images.githubusercontent.com/100976930/206942902-c4e6ff0e-9523-4fda-85f2-d8dcd5d7b8b6.png">

**Comment by gmenounos** [comment]
What kind of cable are you using? What model/year car?

**Comment by blemiee** [comment]
> What kind of cable are you using? What model/year car?

I have a 2013 VW CC and i'm using a Ross-Tech HEX-USB+CAN cable.

**Comment by gmenounos** [comment]
Your car only supports CAN-based diagnostics and kw1281test only supports K-Line-based diagnostics, so unfortunately it's not going to work with your car.
