### ISSUE TITLE
Issue with Polo 9N, also unlock code

### ISSUE THREAD

**Issue by Mr-Ed** [gmenounos/kw1281test#32]
Hi,

I'm having problems getting the SKC out of a Polo 9N with a VDO V18 ECU.

It gives an "Unexpected seed suffix: $03 $00, (Expected $01 $00)" error, and also says "some bytes could not be read and were replaced with a 0".

I've tried doing a full dump and pulling the SKC out manually, but the number I get out doesn't work. Have attached results of the GetSKC and DumpEeprom commands, and also the resulting eeprom dump if it helps...

It also says:
"Unlock code for software version 'VSQX01LM 01.10' is 43 43 3D 37
Please report this to the program maintainer."

Hope you can help, down to one key... :-)

Cheers - Ed

[DumpEeprom.txt](https://github.com/gmenounos/kw1281test/files/10546609/DumpEeprom.txt)
[WVWZZZ9NZ4Y229943_____VWZ7Z0D9081711_$0000_eeprom.txt](https://github.com/gmenounos/kw1281test/files/10546612/WVWZZZ9NZ4Y229943_____VWZ7Z0D9081711_.0000_eeprom.txt)
[GetSKC attempt 1.txt](https://github.com/gmenounos/kw1281test/files/10546657/GetSKC.attempt.1.txt)

**Comment by FaZeIlLuMiNaTi** [comment]
Hi Ed,

Which year was your Polo manufactured? Is it a facelift model? I'm seeing very similar behaviour on a Polo 9n3 (facelift) manufactured in 2005. I've got a VDO V02 cluster.

Did you ever manage to retrieve the SKC?

**Comment by Mr-Ed** [comment]
That would be great if you can, thanks for looking at it!

Mine's a 2004 (54 plate), pre-facelift. Never found a way of getting the SKC out of it, tried loads of different bits of software.

**Comment by dmaniaa** [comment]
Hi. If you have the time, please do attempt to add the support for the 9N clusters, I'm waiting for it, too. I also have the 6Q0 920 800 cluster. Just bumping the issue.

**Comment by chr4ss12** [comment]
same here, would be very appreciated, hard time getting the SKC with any software, don't want to install some chinese clones, happy to support with money

```
Args: COM3 10400 17 GetSKC
OSVersion: Microsoft Windows NT 10.0.22621.0
.NET Version: 8.0.0
Culture: en-US
Opening serial port COM3
Sending wakeup message
Wakeup duration: 2 seconds
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 6Q0920900A KOMBI+WEGFAHRSP VDO V13
Software Coding 01443, Workshop Code: 00000
Sending ReadIdent block
Sending Custom "Read Software Version" blocks
Sending Custom "Unlock Additional Commands" block
00: VSQX01LM $10 $01
01: $69 $19
02: $07 $0B $01 $0B $1B $15
03: PQ24_2 LM KW18/02
Sending Custom "Unlock partial EEPROM read" block
Unlock code for software version 'VSQX01LM 01.10' is 43 43 3D 37
Sending Custom "Need Seed/Key?" block
Sending Custom "Seed request" block
Block:  6C 8A FF D6 3E 71 9B A2 03 00
Unexpected seed suffix: $03 $00, (Expected $01 $00)
Sending Custom "Key response" block
Sending Custom "Need Seed/Key?" block
Failed to unlock cluster.
Saving EEPROM dump to WVWZZZ9NZ3Y070182_____VWZ7Z0B5630989_$0090_eeprom.bin
Sending ReadEeprom block (Address: $0090, Count: $10)
Sending ReadEeprom block (Address: $00A0, Count: $10)
Sending ReadEeprom block (Address: $00B0, Count: $10)
Sending ReadEeprom block (Address: $00C0, Count: $10)
Sending ReadEeprom block (Address: $00D0, Count: $10)
Sending ReadEeprom block (Address: $00E0, Count: $10)
Sending ReadEeprom block (Address: $00F0, Count: $10)
Sending ReadEeprom block (Address: $0100, Count: $0C)

**********************************************************************
*** Warning: Some bytes could not be read and were replaced with 0 ***
**********************************************************************

Saved EEPROM dump to WVWZZZ9NZ3Y070182_____VWZ7Z0B5630989_$0090_eeprom.bin
GetSkc: Unable to find Immobilizer ID in cluster dump.
Unable to determine SKC.
Sending EndCommunication block
```

**Comment by gmenounos** [comment]
After quite a lot of work (buy Polo cluster and BCM, figure out how to wire them up on the bench, download cluster ROM and disassemble seed/key routine), I've added support for the seek/key algorithm used by those Polo clusters: https://github.com/gmenounos/kw1281test/releases/tag/v0.92-beta

@Mr-Ed @FaZeIlLuMiNaTi @dmaniaa @chr4ss12 Please let me know if this new version is able to retrieve the SKC from your clusters.

**Comment by dmaniaa** [comment]
@gmenounos I can confirm, the new version retrieved the SKC without error and I was able to log in and perform immo adaptation in VCDS. Thank you, thank you, thank you, amazing work!
