### ISSUE TITLE
For VWs, this means only MKIV cars are supported

### ISSUE THREAD

**Issue by Bull00Bar** [gmenounos/kw1281test#42]
I am trying to apply kw128test.exe to a 2012 VW CC (3CC) VIN: WVWZZZ3CZCE710268

I assume this is not a MKIV car. Is there a kw128test version that will apply to this VW model?

Thanks

**Comment by gmenounos** [comment]
kw1281test only works with cars that use K-Line diagnostics. Unfortunately the CC uses CAN bus diagnostics, so it's not compatible. Here's a list of VW Group cars that use CAN bus diagnostics: https://www.ross-tech.com/vcds/canbus.php

**Comment by Bull00Bar** [comment]
Thanks for your response Greg. Is there a way to find the SKC for the CC.
At the moment I have an ECU Disabled error. The engine cranks but only runs
for a few seconds.
Regards,
Graeme

**Comment by gmenounos** [comment]
Sorry, I don't know of a way other than via a VW dealer and certain commercial tools (e.g. VagTacho), but I don't know which tools would work with your car.
