### ISSUE TITLE
Support for a new cluster

### ISSUE THREAD

**Issue by neotec-de** [gmenounos/kw1281test#43]
Hi Greg,

is it possible to support the following cluster?
The structure of the eeprom data is very similar to VWK503MH.

<details><summary>Details</summary>
<p>

Version 0.82-beta (https://github.com/gmenounos/kw1281test/releases)
Args: com7 10400 17 ReadSoftwareVersion
OSVersion: Microsoft Windows NT 10.0.22000.0
.NET Version: 7.0.5
Culture: de-DE
Opening serial port com7
Sending wakeup message
Wakeup duration: 2 seconds
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 3BD920848E  KOMBI+WEGFAHRSP VDO V03
Software Coding 04135, Workshop Code: 00000
Sending Custom "Read Software Version" blocks
Sending Custom "Unlock Additional Commands" block
00: VCLM09MH $00 $09
01: $63 $28 
02: $13 $0B $08 $0A $35 $16 
03: B5-Lingyu-MH Maske  
Sending EndCommunication block

</p>
</details> 

I fetch the eeprom per direct access on the PCB by CarProg.
[china_Tacho_Dump.zip](https://github.com/gmenounos/kw1281test/files/11873221/china_Tacho_Dump.zip)

Do you need any further information to implement this new cluster?
For example a dump of the RAM?

Thanks in advance for your help.

Best,
Alex

**Comment by gmenounos** [comment]
Hi Alex,

Based on that EEPROM dump, it looks like the SKC is 03643. Is that correct?

Have you tried the DumpEeprom command to see if that works?

`.\kw1281test com7 10400 17 DumpEeprom 0 2048`

Please attach a log of the above command and if it succeeds I'll try to add support for that cluster.

**Comment by gmenounos** [comment]
Can you attach the LSVET69F3B2430293_____VWZ7Z0J0019359_$0000_eeprom.bin file so I can see what's in there?

Can CarProg dump the ROM? I think that's what I'll need to add support. There's a 4-byte secret key that varies by cluster model. Several common keys are included in kw1281test but it looks like your cluster uses a different key.

**Comment by neotec-de** [comment]
Here the attached file.
[LSVET69F3B2430293_____VWZ7Z0J0019359_$0000_eeprom.zip](https://github.com/gmenounos/kw1281test/files/11919122/LSVET69F3B2430293_____VWZ7Z0J0019359_.0000_eeprom.zip)

CarProg can dump the ROM by soldering the direct wires to the 93c86 on the PCB. No other way is functional (OBD).

**Comment by neotec-de** [comment]
Any progress, or is it still going on?
Is there any way I can support you?

**Comment by gmenounos** [comment]
I don't think I can support this cluster without a dump of the ROM (not the 93c86 EEPROM). Possibly if I had one I could add support but I've searched around and I can't find a way to buy a used 3BD920848E cluster in the US.

**Comment by neotec-de** [comment]
Oh yes. This cluster is only buyable in the local china market.

Is a dump of the RAM a possible way?

**Comment by Schumey** [comment]
I got the same cluster, and I'm currently trying to bruteforce the secret key.

**Comment by Schumey** [comment]
Some dude in a German forum had success and found the secret key which is 32-31-36-31.

**Comment by neotec-de** [comment]
@Schumey 
Thank you for the great info. Could you please share the link with us to the german forum?

@gmenounos 
Is it possible to get a new build for testing?

**Comment by Schumey** [comment]
@neotec-de 
https://www.golf4.de/interieur/204523-passat-lingyu-tacho-4.html#post3379157

**Comment by gmenounos** [comment]
Please try this release and see if it works with that cluster: https://github.com/gmenounos/kw1281test/releases/tag/v0.86-beta

**Comment by neotec-de** [comment]
Works perfect. 
Request can be closed.
