### ISSUE TITLE
Write dump to instrument cluster

### ISSUE THREAD

**Issue by glsmith86** [gmenounos/kw1281test#44]
Hi Everyone!

I have dumped my instrument cluster eeprom. I made some modifications on it and I want upload to the new eeprom to the cluster.

How can I do it? No command for this action.

**Comment by neotec-de** [comment]
It's a Passat New Lingyu cluster. It is based on our Passat 3bg B5.5 in Europe.
Manufacturer is VDO.

<details><summary>Details</summary>
<p>

![IMG_2654](https://github.com/gmenounos/kw1281test/assets/137206154/e1bf343a-0dba-43d3-af9f-a7401785b35f)
![IMG_2655](https://github.com/gmenounos/kw1281test/assets/137206154/90d02352-a7ef-4da8-8c17-b5872c068241)
</p>
</details>

**Comment by glsmith86** [comment]
@gmenounos it's a 3B0920849A instrument cluster in Golf MK4. I want to upload the complet eeprom.

**Comment by gmenounos** [comment]
You would use the LoadEeprom command to load a dump file back into the cluster. I'm pretty sure that only works on VDO clusters, which yours is.
