### ISSUE TITLE
Stops reading Sync Byte

### ISSUE THREAD

**Issue by JonMX43** [gmenounos/kw1281test#47]
Hi i recently come upon your page i am currently renting a HEX CAN cable so im in the hot seat the test stops running at the sync byte saying failed to wakeup. (see attached) i have done every step, twice over and back again to make sure i didnt screw this up. all i need is my SKC to program my new keys. what other info can i provide to get your assistance? i would really appreciate any help.

[KW1281Test.log](https://github.com/gmenounos/kw1281test/files/12101629/KW1281Test.log)

**Comment by gmenounos** [comment]
The HEX+CAN cable should work if you install the VCP drivers: https://www.ross-tech.com/vag-com/usb/virtual-com-port.php
After installing the VCP driver, you will have to run VCDS, go into Options, uncheck "Boot in Intelligent Mode", save the settings then unplug the cable from the PC and plug it back in again. After that it should work with kw1281test.

**Comment by JonMX43** [comment]
I have installed the vcp drivers and unchecked the 'boot in intelligence'
mode that's why I'm asking for help I'm at my wits end lol

**Comment by JonMX43** [comment]
Hey. I'm not sure what I did. Maybe just coming back not frustrated and
checking everything again to make sure it was working properly. But I was
able to get my skc. I am 100% going to donate to you. Do you have a
preferred method? Thank you so much.

-Jon

**Comment by gmenounos** [comment]
Glad you got it working. To donate, go to the [main kw1281test page](https://github.com/gmenounos/kw1281test) and on the right side there is a "Sponsor this project" link.
