### ISSUE TITLE
Error during sync byte

### ISSUE THREAD

**Issue by Mk4derek** [gmenounos/kw1281test#48]
![Uploading image.jpg…]()
When attempting to retrieve the skc I am getting an error system.invalidoperationexception nogcregion mode must be set.

**Comment by gmenounos** [comment]
Please attach kw1281test.log

**Comment by Mk4derek** [comment]
[KW1281Test.log](https://github.com/gmenounos/kw1281test/files/12446565/KW1281Test.log)

**Comment by Mk4derek** [comment]
@gmenounos any input?

**Comment by gmenounos** [comment]
Try this new version and see if it fixes it: https://github.com/gmenounos/kw1281test/releases/tag/v0.84-beta

**Comment by Mk4derek** [comment]
[KW1281Test.log](https://github.com/gmenounos/kw1281test/files/12808917/KW1281Test.log)
"Unable to skc. Cluster not in new mode (4) ?"
@gmenounos

**Comment by gmenounos** [comment]
Instructions on how to retrieve the SKC from an Audi RB4 cluster are here: [https://github.com/gmenounos/kw1281test/releases/tag/v0.77-beta](https://github.com/gmenounos/kw1281test/releases/tag/v0.77-beta)

**Comment by Mk4derek** [comment]
@gmenounos it worked!! Even with my dodgy third party OBD cable. Thank you for the support I really appreciate the help.

**Comment by gmenounos** [comment]
Glad it worked for you.
