### ISSUE TITLE
7H5 cluster support

### ISSUE THREAD

**Issue by covex** [gmenounos/kw1281test#49]
I finally managed to overcome all cable/SW issues, to get the kw1281test running. However the read of SKC does not work on that cluster (VW T5 2008). 

Here is the output, that asks me to report the code to the maintainer:
[output.txt](https://github.com/gmenounos/kw1281test/files/12670398/output.txt)

I can also provide DumpEeprom 0 2048 or anything..

**Comment by covex** [comment]
If I understand correctly, this cluster is also having a different change/response (seed/key) used.
https://forums.tdiclub.com/index.php?threads/kw1281test-a-free-vds-pro-vagtacho-alternative.509151/page-39#post-5775996
Thus this does not unlock the eeprom range 0x70-0x13F where probably could be the SKC. This address range is then filled with 0x00 in dump. Otherwise the rest of the dump seems pretty OK.

**Comment by covex** [comment]
Here somebody uses vagtach on T5
https://blog.t49.net/vw-t5-transporter-dashpod-hacking/
there obviously is a different seed/key "mode". I think there will be just different "secret" used because the cluster is otherwise the same as MKIV.  I.e. the CalculateKey() is using  0x55, 0x16, 0xa8, 0x94 but I guess there will be different values for mode "03".

**Comment by gmenounos** [comment]
I'll probably need to get ahold of one of these clusters in order to add support. I'll see if I can find an inexpensive on eBay. If you have any ideas, please let me know.

**Comment by covex** [comment]
Oh, great - I just do not see any new commits, I'll wait for next release to test as I do not have a C# build environemt I guess.
