### ISSUE TITLE
Feature request / idea

### ISSUE THREAD

**Issue by Rebiaf** [gmenounos/kw1281test#5]
Would you be interested adding feature to read & write old airbag modules like 1C0 909 605 B and similar models with siemens HC12 processor with internal eeprom. I have collection of unlock codes somewhere and will find and post here if you like.  Might not be any more difficult than cluster stuff.

**Comment by gmenounos** [comment]
Sure, I'll give it a try. I have some airbag modules that I can test with. Just let me know what the unlock codes are and any other info you have.

**Comment by gmenounos** [comment]
> Would you be interested adding feature to read & write old airbag modules like 1C0 909 605 B and similar models with siemens HC12 processor with internal eeprom. I have collection of unlock codes somewhere and will find and post here if you like. Might not be any more difficult than cluster stuff.

Just a reminder to send me the airbag codes if you'd like me to try to add that feature.
