### ISSUE TITLE
Controller did not wake up (HEX V1 cable)

### ISSUE THREAD

**Issue by AdisonCavani** [gmenounos/kw1281test#52]
Hello. I cannot connect to any module (ECU & instrument cluster). The process is visible on the video.
I'm using HEX V1 cable with COM drivers.

I ordered a VAG KKL cable for testing if it's my cable fault / missconfiguration.
I'll give you an update on this issue.

Car specification:
Skoda Fabia sedan mk1, 2002, 1.4MPi 68HP 50kW. It's using k-line kw1281 protocol.

https://github.com/gmenounos/kw1281test/assets/76855180/1c3898ab-5f1e-49cc-a8fd-212a50dabce5

![Zrzut ekranu 2023-12-18 170441](https://github.com/gmenounos/kw1281test/assets/76855180/5f8c95ef-3488-471a-9c94-97c35b6685ee)
![Zrzut ekranu 2023-12-18 170342](https://github.com/gmenounos/kw1281test/assets/76855180/4184505c-f441-4269-ba43-517cc5a89da8)
![Zrzut ekranu 2023-12-18 170352](https://github.com/gmenounos/kw1281test/assets/76855180/48fb766d-f071-4129-bb0f-0076a265cbfb)
![Zrzut ekranu 2023-12-18 170432](https://github.com/gmenounos/kw1281test/assets/76855180/8d771af8-92ac-4039-ac1d-cc66e48ab485)
![Zrzut ekranu 2023-11-06 194318](https://github.com/gmenounos/kw1281test/assets/76855180/33084fa8-12e7-4d0f-8933-176abc5da4c2)

**Comment by gmenounos** [comment]
Thanks for the detailed video/photos. You might need to disable the "Boot in Intelligent Mode" setting as explained here: https://forums.tdiclub.com/index.php?threads/kw1281test-a-free-vds-pro-vagtacho-alternative.509151/page-12#post-5638868

**Comment by AdisonCavani** [comment]
The VAG KKL cable arrived and it's working.

I tried to read the Instrument Cluster SKC, but it's not working (it's not important for me, because I know the code).

I also tried to `WriteEeprom` and activate windows roll up/down via remote pilot.

My comfort module: `6Q0 959 433 E`.

| Address         | Old value | New value |
|-----------------|-----------|-----------|
| 04361           | 138       | 130       |
| 04362           | 138       | 130       |
| 04363           | 138       | 130       |
| ---             | ---       | ---       |
| **Front driver**    |           |           |
| 08224           | 79        | 95        |
| 08269           | 79        | 95        |
| 08314           | 79        | 95        |
| ---             | ---       | ---       |
| **Front passenger** |           |           |
| 12320           | 79        | 95        |
| 12365           | 79        | 95        |
| 12410           | 79        | 95        |

After this changes, the module is responding to `ReadIdent` and other commands.
However the windows are not rolling up or down via remote pilot.

When I press and hold lock (or unlock) button on pilot, the windows are not moving up (or down).

**Comment by gmenounos** [comment]
I only support kw1281test being able to read/write to the CCM. For help with what values work for your particular CCM, try asking in the following TDIClub threads:

- https://forums.tdiclub.com/index.php?threads/coding-procedure-for-ccm-window-modification.151041/
- https://forums.tdiclub.com/index.php?threads/additional-ccm-coding-and-configurations-with-vds-pro.160960/
