### ISSUE TITLE
Possible TypeLoadException fix

### ISSUE THREAD

**Issue by IJskonijn** [gmenounos/kw1281test#6]
Maybe try:
Process.GetCurrentProcess().PriorityClass = ProcessPriorityClass.High;

This could help solve the TypeLoadException because the RealTime prio requires extra privileges.
I've tried it locally and it works without errors, not sure if it will affect the timing loops tho.

Source:
[https://stackoverflow.com/questions/1663993/what-is-the-realtime-process-priority-setting-for](https://stackoverflow.com/questions/1663993/what-is-the-realtime-process-priority-setting-for)

**Comment by gmenounos** [comment]
I don't think that is actually the issue. If I set priority to RealTime and run the app as a regular user, instead of throwing an exception, the process priority gets set to High. If I open a console as administrator and run the app, the priority gets set to RealTime. I've been unable to repro the TypeLoadException on my dev machines. Have you been able to?

**Comment by IJskonijn** [comment]
Yes, but only with a published version downloaded from github, which is weird...
If I build it myself and run debug or release version from a non-administrator powershell window, it works just fine. 
No exceptions...
When I use the github version it always gives me the exception, even if I run powershell in admin mode.

I will try to debug it some more

**Comment by gmenounos** [comment]
It could be one of the publishing settings that I use when I build the version for GitHub. I’m going to guess that it’s the PublishTrimmed setting. Maybe it’s trimming a little too much.

 

<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <PropertyGroup>

    <Configuration>Release</Configuration>

    <Platform>Any CPU</Platform>

    <PublishDir>bin\Release\net5.0\publish\Win</PublishDir>

    <PublishProtocol>FileSystem</PublishProtocol>

    <TargetFramework>net5.0</TargetFramework>

    <SelfContained>true</SelfContained>

    <RuntimeIdentifier>win-x86</RuntimeIdentifier>

    <PublishSingleFile>True</PublishSingleFile>

    <PublishReadyToRun>False</PublishReadyToRun>

    <PublishTrimmed>True</PublishTrimmed>

  </PropertyGroup>

</Project>

**Comment by IJskonijn** [comment]
Good catch, maybe it's missing some api's.
You can also try using <TrimMode>CopyUsed</TrimMode> in the csproj file. 
This should be a somewhat safer form of trimming.

Source:
[https://devblogs.microsoft.com/dotnet/app-trimming-in-net-5/](https://devblogs.microsoft.com/dotnet/app-trimming-in-net-5/)

**Comment by gmenounos** [comment]
Would you mind giving this version a try? I added some more debug info to try to track down the source of the exceptions.
https://github.com/gmenounos/kw1281test/releases/download/v0.58-beta/kw1281test_0.58-beta_Win10_Debug.zip

**Comment by IJskonijn** [comment]
Looks a lot better!
Here is a quick log:

`KW1281Test 0.58-beta (https://github.com/gmenounos/kw1281test/releases)
Args: com2 10400 17 GetSKC
OSVersion: Microsoft Windows NT 10.0.17134.0
.NET Version: 5.0.7
Culture: nl-NL
Opening serial port com2
Sending wakeup message
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 3U0920810A  KOMBI+WEGFAHRSP VDO V02
Software Coding 31115, Workshop Code: 00000
Cluster is non-Immo so there is no SKC.
Sending EndCommunication block
KW1281Test 0.58-beta (https://github.com/gmenounos/kw1281test/releases)
Args: com2 10400 17 ReadSoftwareVersion
OSVersion: Microsoft Windows NT 10.0.17134.0
.NET Version: 5.0.7
Culture: nl-NL
Opening serial port com2
Sending wakeup message
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 3U0920810A  KOMBI+WEGFAHRSP VDO V02
Software Coding 31115, Workshop Code: 00000
Sending Custom "Read Software Version" blocks
Sending Custom "Unlock Additional Commands" block
00: VWK501LL $00 $01 
01: $75 $18 
02: $09 $05 $01 $0A $0F $37 
03: VW/Sk LL Serie Maske
Sending EndCommunication block
KW1281Test 0.58-beta (https://github.com/gmenounos/kw1281test/releases)
Args: com2 10400 17 ActuatorTest
OSVersion: Microsoft Windows NT 10.0.17134.0
.NET Version: 5.0.7
Culture: nl-NL
Opening serial port com2
Sending wakeup message
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 3U0920810A  KOMBI+WEGFAHRSP VDO V02
Software Coding 31115, Workshop Code: 00000
Sending actuator test 0x00 block
Received "Actuator Test Response" block: 02 96
Actuator Test: Tachometer
Sending actuator test 0x00 block
Received "Actuator Test Response" block: 02 95
Actuator Test: Coolant Temp Gauge
Sending EndCommunication block
`

**Comment by gmenounos** [comment]
Oddly, that version is even more trimmed than the old version, and yet it now works. I think the issue was that I was trimming when publishing before and I've changed it to trim when building instead. Maybe the trim that occurred when publishing was buggy and was trimming out some types that were actually needed.
