### ISSUE TITLE
Unexpected sync byte

### ISSUE THREAD

**Issue by AlLurker** [gmenounos/kw1281test#68]
Hi i am getting an unexpected sync byte message along with controller did not wake up with any command i try. maybe its me being new to this sort of thing but i feel as though i have followed instructions thoroughly. Vehicle is 2000 jetta tdi edc15

thank you for any help
Ryan
![025EC586-4DF7-406F-9D65-0B3982F226A1](https://github.com/gmenounos/kw1281test/assets/165849802/47591255-334d-47db-b81b-bccf0f4c30c2)
![99297AEA-8A44-4ECD-9B58-929C790F3C4A](https://github.com/gmenounos/kw1281test/assets/165849802/728e441c-09d5-4ff6-a791-5929f1eff2c6)

**Comment by ChrstphrR** [comment]
The 9600 baud sticks out like a sore thumb:

https://github.com/gmenounos/kw1281test/wiki#vehicle-controllers-electronic-modules
> 17 - Instruments (instrument cluster - speedometer, tachometer et al.) - 10400 baud (usually), 9600 baud (sometimes)

While you did not mention which cluster you're trying to use, MOST of the clusters use 10400 as the baud rate for these commands, not 9600.

**Comment by gmenounos** [comment]
Yes, a Jetta would use 10400. A Beetle (and maybe Audi TT) would use 9600.

**Comment by AlLurker** [comment]
I have tried with both baud rates with the same result.

**Comment by AlLurker** [comment]
Actually i never changed the rate for the higher one in my device settings, it works now! Thank you! 👍

**Comment by gmenounos** [comment]
👍

**Comment by arathburgos05** [comment]
> Actually i never changed the rate for the higher one in my device settings, it works now! Thank you! 👍

What baudrate did you selected? I cannot se 10400 in Windows Settings:
![image](https://github.com/gmenounos/kw1281test/assets/25379464/a5a61201-2bc8-40e0-a7f2-fc77d530a422)

Regards.

**Comment by AlLurker** [comment]
Im no computer guru by any means but i just select a baud rate higher than 10400 and it worked, im guessing that number is where it caps at
