### ISSUE TITLE
Unsupported Cluster 8N1920880A (Audi TT 1999)

### ISSUE THREAD

**Issue by dskoro** [gmenounos/kw1281test#78]
Hello!

Trying to get the SKC for my car, but run into an error

Could you please add support of this cluster?

Here's the out:
```
PS C:\Users\dmitr> c:\1\kw1281test.exe COM2 9600 17 GetSKC
>>
KW1281Test: Yesterday's diagnostics...Today.

Version 0.97.0-beta (https://github.com/gmenounos/kw1281test/releases)
Args: COM2 9600 17 GetSKC
OSVersion: Microsoft Windows NT 10.0.22631.0
.NET Version: 8.0.0
Culture: en-US
Opening serial port COM2
Sending wakeup message
Reading sync byte
Keyword Lsb $01
Keyword Msb $8A
Protocol is KW 1281 (8N1)
ECU: 8N1920880A  KOMBI+WEGFAHRS. M73 D24
Software Coding 04144, Workshop Code: 40512
Caught: System.InvalidOperationException Unsupported cluster version.
Unhandled exception: System.InvalidOperationException: Unsupported cluster version.
   at BitFab.KW1281Test.Cluster.MarelliCluster.GetDefaultAddress() in /Users/gmenounos/src/kw1281test/Cluster/MarelliCluster.cs:line 38
   at BitFab.KW1281Test.Cluster.MarelliCluster.DumpEeprom(Nullable`1, Nullable`1, String ) in /Users/gmenounos/src/kw1281test/Cluster/MarelliCluster.cs:line 18
   at BitFab.KW1281Test.Tester.GetSkc() in /Users/gmenounos/src/kw1281test/Tester.cs:line 616
   at BitFab.KW1281Test.Program.Run(String[]) in /Users/gmenounos/src/kw1281test/Program.cs:line 275
   at BitFab.KW1281Test.Program.Main(String[]) in /Users/gmenounos/src/kw1281test/Program.cs:line 31

```

**Comment by dskoro** [comment]
[marelli_mem_$0C00 - Copy.txt](https://github.com/gmenounos/kw1281test/files/15368739/marelli_mem_.0C00.-.Copy.txt)

Here's my dump

**Comment by dskoro** [comment]
Tried to find the offset as described here https://github.com/gmenounos/kw1281test/issues/50#issuecomment-1770255129

PIN looks to be 08179, but the car didn't accept it

**Comment by gmenounos** [comment]
That SKC should be correct. I did some searching and found this page where someone uploaded a dump from the same cluster and the SKC was in the same location that you found it and the user verified that the SKC was correct: https://nefariousmotorsports.com/forum/index.php?topic=20717.0title=

**Comment by dskoro** [comment]
@gmenounos hmmm, that's funny, because I tried with two different programs (VAG Commander and russian VD) to log in, and both times god FAIL text on the dash

![image](https://github.com/gmenounos/kw1281test/assets/59956911/197b1bd3-8e27-4097-bb52-fb8c62c21f5c)

**Comment by dskoro** [comment]
okay, tried the same pin again, now it works, added one more key to immo. both keys are working, however, now have the Immo Indicator always on 

don't you know what could it mean in this situation?

![image](https://github.com/gmenounos/kw1281test/assets/59956911/2719bb9c-4749-4d63-9cd8-5ddb21fd77b2)
