### ISSUE TITLE
2000 Golf 2.8 v6 skc

### ISSUE THREAD

**Issue by veWill** [gmenounos/kw1281test#81]
Hi! I got got two similar Golf's, one from 2003 BDE engine and other 2000 AUE engine. I was able to get skc from 2003 first try no problem, but older one resisted a lot. Left my laptop in car and 4 hours later it finally got skc out with latest v0.98 beta. Code seems to be right one, but end of the log said to report to program maintainer.
[KW1281Test.log](https://github.com/user-attachments/files/15952918/KW1281Test.log)
[Ident.-Nr._WEGFAHRS.XVWZ6Z0Y2014104X_$0000_eeprom.zip](https://github.com/user-attachments/files/15952961/Ident.-Nr._WEGFAHRS.XVWZ6Z0Y2014104X_.0000_eeprom.zip)

**Comment by gmenounos** [comment]
Thanks for providing this info.
