### ISSUE TITLE
Support for china 1JD clusters

### ISSUE THREAD

**Issue by cr4ck3dn** [gmenounos/kw1281test#83]
Hello, thanks for this program. 
It is possible to add support for china clusters 1JD 920 826 instruments clusters? I need security acces key to read eeprom via obd. Eeprom is 501 and can be downloaded here: https://drive.google.com/file/d/1jYovyTkejqLjwygkHkuKW5CZvgzSC2ns/view?fbclid=IwY2xjawD9AzdleHRuA2FlbQIxMQABHXg6wKJ-Zsi1xilyKe5B0pxkSbODA-dsR6ucLdsqQG5bt5BRM2d40lepbw_aem_2uFLaJylDp5A_GqoVlmvoQ
![17207222867177337965984229656775](https://github.com/gmenounos/kw1281test/assets/28197628/847a2ec2-e3b6-4328-a11c-f25594cc8ae9)

**Comment by gmenounos** [comment]
At offset 0x436 and 0x437 in the EEPROM are 2 values: 0xA6 0x84.
Try changing those to 0x79 0x57 and that should unlock the cluster and allow you to read/write the EEPROM with kw1281test over OBD. If that works, then I'd like you to send me a ROM dump so I can add support for unlocking that cluster. Will send instructions for that if you're able to unlock via the above method.

**Comment by cr4ck3dn** [comment]
Hello, sorry for late reply (broken old laptop).
I have successfully read Rom , EEPROM with your software.
I have uploaded all read data from clusters and some photos.
Acces code seems to be 33 , 34 , 46 , 4A?!
You can download the file here:
1JD920826E-VCB07LL-ROM.RAM.EEPROM.PHOTOS.rar
https://disk.yandex.com/d/QVEzMRofvt7log

**Comment by gmenounos** [comment]
Thanks! However, I noticed that when you dumped the last part of the ROM, it timed out and didn't get the whole thing. Can you run this command one more time and share the file that it produces?

```
kw1281test.exe COM1 10400 17 DumpMem $48000 $4000
```

**Comment by cr4ck3dn** [comment]
Hmm I don't know why timed out...
It's ok now?
You can download the file here:
cluster_mem_$048000.bin
https://disk.yandex.com/d/0UXdEf6Yzg767w

**Comment by gmenounos** [comment]
That file is truncated. It's 3855 bytes long but it should be 16384 bytes long. kw1281test.log shows that there was a timeout trying to read that part of the ROM:

Sending Custom "Read Memory" block (Address: $048F0F, Count: $0F)
Error receiving block: The operation has timed out.
Partial block: $12 $15 $1B $80 $05 $A9 $08 $1C $AB $06 $60 $A9 
Read timeout: 8000
Write timeout: 8000
Error receiving blocks: The operation has timed out.
Caught: System.TimeoutException The operation has timed out.

**Comment by cr4ck3dn** [comment]
I read it completely again.
It appears to be the size you specified.I also checked the log file and found no time out.
Thanks! 
You can download the file here:
1jd920826e_mem.rar
https://disk.yandex.com/d/EBR1G6tpVEpuMQ

**Comment by gmenounos** [comment]
I've released a new version that should support that cluster:
https://github.com/gmenounos/kw1281test/releases/tag/v0.99.3-beta
Please give it a try and let me know if it works. If it doesn't work I'll re-open this issue.
