### ISSUE TITLE
Ross-Tech HEX-COM+CAN Supported?

### ISSUE THREAD

**Issue by Trade-Script** [gmenounos/kw1281test#88]
I have a Legacy Ross-Tech HEX-COM+CAN cable that I use to run VCDS on a 2001 VW Golf GLS 1.8T, which it does flawlessly, on a Windows 10 laptop with a _native serial port_ running on COM1.

I have tried running kw128test multiple times unsuccessfully using both 9600 and 10400 baud. Always get the `Caught: System.InvalidOperationException Controller did not wake up` fault.

Is this cable even supported or am I out of luck and need to purchase a KKL USB cable? Willing to play with some settings if that might help.

Here is my most recent log:

Version 0.99.2-alpha (https://github.com/gmenounos/kw1281test/releases)
Args: COM1 9600 17 GetSKC
OSVersion: Microsoft Windows NT 10.0.19045.0
.NET Version: 8.0.6
Culture: en-US
Opening serial port COM1
Sending wakeup message
Reading sync byte
Unexpected sync byte: Expected $55, Actual $B5
Retrying wakeup message...
Reading sync byte
Unexpected sync byte: Expected $55, Actual $B5
Retrying wakeup message...
Reading sync byte
Unexpected sync byte: Expected $55, Actual $95
Caught: System.InvalidOperationException Controller did not wake up.
Unhandled exception: System.InvalidOperationException: Controller did not wake up.
   at BitFab.KW1281Test.KwpCommon.WakeUp(Byte, Boolean) in /Users/gmenounos/src/kw1281test/KwpCommon.cs:line 62
   at BitFab.KW1281Test.Tester.Kwp1281Wakeup(Boolean ) in /Users/gmenounos/src/kw1281test/Tester.cs:line 33
   at BitFab.KW1281Test.Tester.GetSkc() in /Users/gmenounos/src/kw1281test/Tester.cs:line 509
   at BitFab.KW1281Test.Program.Run(String[]) in /Users/gmenounos/src/kw1281test/Program.cs:line 275
   at BitFab.KW1281Test.Program.Main(String[]) in /Users/gmenounos/src/kw1281test/Program.cs:line 31

**Comment by kerekt** [comment]
Hi!
I'm using same hex-com+can long time, for me working good.
Try switch to Dumb mode, after com test in vcds under options menu
regards

**Comment by Trade-Script** [comment]
Finally had some time to re-test this weekend. As @kerekt suggested, I had attempted using dumb mode, but it was unsuccessful with similar results to my op above. Thankfully this set-up did end up working.

Within VCDS:
Click "Restore Defaults"
Uncheck "Boot in intelligent mode"
Do a "Test" then click "Save" and exit VCDS

Next run kw1281test with _10400 baud_:
KW1281Test COM1 10400 17 GetSKC

I think restoring defaults may have been the key for me in addition to using dumb mode. Ghost in the machine for sure! I was also surprised that 10400 was needed as 9600 has been the common suggestion for my model and make, but obviously the control units are not consistent. In any case all of my testing has now been successful and I have the SKC for my car.

Thanks to @gmenounos for this awesome piece of software and @kerekt for your reply. Cheers!
