### ISSUE TITLE
Run on WinXP

### ISSUE THREAD

**Issue by gmarco98** [gmenounos/kw1281test#94]
Hi,

Im running my 311-n vagcom on a VM, winXP. Is there a way to make it work there? And how so?

Thank you

**Comment by gmenounos** [comment]
The last version that supports WinXP is 0.27 but it's really old: https://github.com/gmenounos/kw1281test/releases/tag/v0.27-beta
Unfortunately kw1281test now requires a version of .NET that does not support WinXP and I no longer have a WinXP machine so I wouldn't be able to test it even if it was supported.
