### ISSUE TITLE
Cluster škoda fabia MK2 5J0920810b

### ISSUE THREAD

**Issue by KRYSM4N** [gmenounos/kw1281test#98]
Hello, I need help with the gauges from the Škoda Fabia II. I need to find out the CAN IDs or any guide on how to obtain them so I can activate them in SimHub and then play ETS2 while sending data from the game to the CAN bus MCP2515. I have been looking for these IDs for two weeks and have only found the ones for the tachometer and turn signals (0x280, 0x470). If anyone has all the CAN IDs for these gauges, I would greatly appreciate it. Thank you so much! <3
![2d99aa87-21ae-4746-bfde-1c3f2c31f20e](https://github.com/user-attachments/assets/c542b9d9-2f2d-47e9-bb70-24489f190fc9)

**Comment by gmenounos** [comment]
Sorry, kw1281test does not support CAN bus.
