### ISSUE TITLE
VW Caddy 2009 - Controller did not wake up - GetSKC 

### ISSUE THREAD

**Issue by krizad120** [gmenounos/kw1281test#99]
Hi,
I'm getting the following message.
Could you provide any help? Is it the cable or am I doing something wrong?
Thanks in advance

`Version 0.99.2-alpha (https://github.com/gmenounos/kw1281test/releases)
Args: COM2 10400 17 GetSKC
OSVersion: Microsoft Windows NT 10.0.22631.0
.NET Version: 8.0.6
Culture: cs-CZ
Opening serial port COM2
Sending wakeup message
Reading sync byte
The operation has timed out.
Retrying wakeup message...
Reading sync byte
The operation has timed out.
Retrying wakeup message...
Reading sync byte
The operation has timed out.
Caught: System.InvalidOperationException Controller did not wake up.
Unhandled exception: System.InvalidOperationException: Controller did not wake up.
   at BitFab.KW1281Test.KwpCommon.WakeUp(Byte, Boolean) in /Users/gmenounos/src/kw1281test/KwpCommon.cs:line 62
   at BitFab.KW1281Test.Tester.Kwp1281Wakeup(Boolean ) in /Users/gmenounos/src/kw1281test/Tester.cs:line 33
   at BitFab.KW1281Test.Tester.GetSkc() in /Users/gmenounos/src/kw1281test/Tester.cs:line 509
   at BitFab.KW1281Test.Program.Run(String[]) in /Users/gmenounos/src/kw1281test/Program.cs:line 275
   at BitFab.KW1281Test.Program.Main(String[]) in /Users/gmenounos/src/kw1281test/Program.cs:line 31
`

**Comment by kerekt** [comment]
caddy 2009 not using K-line anymore,  its CAN based. So kw1281test  not support this type of clusters.

**Comment by krizad120** [comment]
I guess I'm out of luck then. Thanks for the help anyway :)

**Comment by gmenounos** [comment]
Thanks for the info @kerekt
I need to write up some documentation about which clusters are supported and which aren't.

**Comment by kerekt** [comment]
Hi! Easy , i will help you to make doc, give me some days!

**Comment by gmenounos** [comment]
Thanks! I see that you emailed me the list a few days ago but it was from a different name so I didn't realize it was you.

**Comment by gmenounos** [comment]
I put your document on the Wiki: https://github.com/gmenounos/kw1281test/wiki/Supported-Clusters
Feel free to edit it as needed.
I probably need to combine it with https://github.com/gmenounos/kw1281test/wiki/Known-working-VW-Audi-platforms
